# Generated by Django 3.2.9 on 2021-12-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chipmunk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSecret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chipmunk.usermanager")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
